-- Ejecutar una sola vez en SQL Developer, conectado al mismo usuario de .env.
-- No borra productos, precios ni ventas existentes.

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTOS ADD (STOCK NUMBER DEFAULT 0 NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE DETALLE_VENTAS ADD (CANTIDAD NUMBER DEFAULT 1 NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PRODUCTOS START WITH 100 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PRECIOS START WITH 100 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_VENTAS START WITH 100 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMIT;