-- Esquema Oracle para CUBICREP'S.
-- Ejecutar conectado al usuario que usa la aplicacion en SQL Developer.

-- 1. Tabla de tamanos (reintegrada para mantener control)
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE TAMANOS (
    ID_TAMANO NUMBER(10) CONSTRAINT PK_TAMANOS PRIMARY KEY,
    TAMANO VARCHAR2(20) NOT NULL
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2. Tabla de Pagos
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE PAGOS (
    ID_PAGO NUMBER(10) CONSTRAINT PK_PAGOS PRIMARY KEY,
    METODO_PAGO VARCHAR2(20) NOT NULL CONSTRAINT UQ_PAGOS_METODO UNIQUE
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 3. Tabla de Productos
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE PRODUCTOS (
    ID_PRODUCTO NUMBER(10) CONSTRAINT PK_PRODUCTOS PRIMARY KEY,
    NOMBRE_PRODCUTO VARCHAR2(100) NOT NULL,
    STOCK NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT CK_PRODUCTOS_STOCK CHECK (STOCK >= 0)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 4. Tabla de Precios
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE PRECIOS (
    ID_PRECIO NUMBER(10) CONSTRAINT PK_PRECIOS PRIMARY KEY,
    ID_PRODUCTO NUMBER(10) NOT NULL,
    ID_TAMANO NUMBER(10) NOT NULL,
    PRECIO NUMBER(10,2) NOT NULL,
    CONSTRAINT CK_PRECIOS_PRECIO CHECK (PRECIO >= 0),
    CONSTRAINT FK_PRECIOS_PRODUCTO FOREIGN KEY (ID_PRODUCTO)
      REFERENCES PRODUCTOS (ID_PRODUCTO),
    CONSTRAINT FK_PRECIOS_TAMANO FOREIGN KEY (ID_TAMANO)
      REFERENCES TAMANOS (ID_TAMANO),
    CONSTRAINT UQ_PRECIOS_PRODUCTO_TAM UNIQUE (ID_PRODUCTO, ID_TAMANO)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 5. Tabla de Ventas
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE VENTAS (
    NUM_VENTA NUMBER(10) CONSTRAINT PK_VENTAS PRIMARY KEY,
    FECHA_VENTA DATE DEFAULT SYSDATE NOT NULL,
    ID_PAGO NUMBER(10) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_VENTAS_PAGO FOREIGN KEY (ID_PAGO)
      REFERENCES PAGOS (ID_PAGO)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 6. Tabla de Detalle de Ventas
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE DETALLE_VENTAS (
    NUM_VENTA NUMBER(10) NOT NULL,
    ID_PRODUCTO NUMBER(10) NOT NULL,
    ID_TAMANO NUMBER(10) NOT NULL,
    ID_PRECIO NUMBER(10) NOT NULL,
    TOTAL NUMBER(10,2) NOT NULL,
    CANTIDAD NUMBER(10) NOT NULL,
    CONSTRAINT PK_DETALLE_VENTAS PRIMARY KEY (NUM_VENTA, ID_PRODUCTO),
    CONSTRAINT CK_DETALLE_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_DETALLE_TOTAL CHECK (TOTAL >= 0),
    CONSTRAINT FK_DETALLE_VENTA FOREIGN KEY (NUM_VENTA)
      REFERENCES VENTAS (NUM_VENTA),
    CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (ID_PRODUCTO)
      REFERENCES PRODUCTOS (ID_PRODUCTO),
    CONSTRAINT FK_DETALLE_PRECIO FOREIGN KEY (ID_PRECIO)
      REFERENCES PRECIOS (ID_PRECIO)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Secuencias
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PRODUCTOS START WITH 21 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PRECIOS START WITH 21 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_VENTAS START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Insercion de tamanos iniciales (chico, mediano, grande)
MERGE INTO TAMANOS destino
USING (
  SELECT 1 AS ID_TAMANO, 'Chico' AS TAMANO FROM DUAL UNION ALL
  SELECT 2, 'Mediano' FROM DUAL UNION ALL
  SELECT 3, 'Grande' FROM DUAL
) origen ON (destino.ID_TAMANO = origen.ID_TAMANO)
WHEN NOT MATCHED THEN INSERT (ID_TAMANO, TAMANO) VALUES (origen.ID_TAMANO, origen.TAMANO);

-- Inserción de Métodos de Pago
MERGE INTO PAGOS destino
USING (
  SELECT 1 AS ID_PAGO, 'efectivo' AS METODO_PAGO FROM DUAL UNION ALL
  SELECT 2, 'tarjeta' FROM DUAL
) origen ON (destino.ID_PAGO = origen.ID_PAGO)
WHEN NOT MATCHED THEN INSERT (ID_PAGO, METODO_PAGO) VALUES (origen.ID_PAGO, origen.METODO_PAGO);

-- Inserción de Productos
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 1, 'Crepa de Nutella', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 1);

INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 2, 'Crepa de Jamon y Queso', 15 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 2);

INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 3, 'Crepa de Cajeta', 25 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 3);

INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 4, 'Crepa de Pollo', 12 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 4);

-- Inserción de Precios (asociados al tamaño 3 'Grande')
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 1, 1, 3, 65 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 1);

INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 2, 2, 3, 75 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 2);

INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 3, 3, 3, 60 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 3);

INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 4, 4, 3, 85 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 4);

-- Catalogo adicional de crepas y frapes
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 5, 'Crepa de Fresa', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 5);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 6, 'Crepa de Oreo', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 6);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 7, 'Crepa de Mango', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 7);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 8, 'Crepa de Manzana y Canela', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 8);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 9, 'Crepa de Tres Leches', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 9);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 10, 'Crepa de Queso y Zarzamora', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 10);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 11, 'Crepa de Choco Banano', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 11);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 12, 'Crepa Mexicana', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 12);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 13, 'FRAPPE de Oreo', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 13);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 14, 'FRAPPE de Moka', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 14);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 15, 'FRAPPE de Caramelo', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 15);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 16, 'FRAPPE de Fresa', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 16);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 17, 'FRAPPE de Chocolate', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 17);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 18, 'FRAPPE de Vainilla', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 18);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 19, 'FRAPPE de Cajeta', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 19);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODCUTO, STOCK)
SELECT 20, 'FRAPPE de Cookies', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTOS WHERE ID_PRODUCTO = 20);

INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 5, 5, 3, 70 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 5);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 6, 6, 3, 75 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 6);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 7, 7, 3, 70 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 7);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 8, 8, 3, 68 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 8);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 9, 9, 3, 80 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 9);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 10, 10, 3, 78 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 10);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 11, 11, 3, 75 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 11);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 12, 12, 3, 82 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 12);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 13, 13, 3, 65 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 13);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 14, 14, 3, 60 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 14);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 15, 15, 3, 65 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 15);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 16, 16, 3, 60 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 16);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 17, 17, 3, 65 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 17);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 18, 18, 3, 55 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 18);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 19, 19, 3, 65 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 19);
INSERT INTO PRECIOS (ID_PRECIO, ID_PRODUCTO, ID_TAMANO, PRECIO)
SELECT 20, 20, 3, 70 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRECIOS WHERE ID_PRECIO = 20);

COMMIT;
